name: Jira Issue Edit
description: Update changed issue content to Jira
inputs:
  issue:
    description: Key of the issue to be transitioned
    required: true
  summary:
    description: Issue summary
    required: false
  description:
    description: Issue description
    required: false
  fields:
    description: Additional fields in JSON format
    required: false
runs:
  using: 'node16'
  main: './dist/index.js'
